version: '3.8'

services:
  postgres:
    image: postgres:17
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - '5432:5432'

  strapi:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
    ports:
      - '1338:1337'
    volumes:
      - strapidata:/opt/data
    depends_on:
      - postgres

volumes:
  pgdata:
  strapidata: